/*
 * TicTacToe
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the io.swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModelProperty;

/**
 * Move
 */
@javax.annotation.Generated(value = "io.io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2017-03-21T18:30:20.420Z")
public class Move   {
  @JsonProperty("playerName")
  private String playerName = null;

  /**
   * Gets or Sets gameMove
   */
  public enum GameMoveEnum {
    UPPERLEFT("UPPERLEFT"),
    
    UPPERMID("UPPERMID"),
    
    UPPERRIGHT("UPPERRIGHT"),
    
    MIDLEFT("MIDLEFT"),
    
    MIDMID("MIDMID"),
    
    MIDRIGHT("MIDRIGHT"),
    
    LOWERLEFT("LOWERLEFT"),
    
    LOWERMID("LOWERMID"),
    
    LOWERRIGHT("LOWERRIGHT");

    private String value;

    GameMoveEnum(String value) {
      this.value = value;
    }

    @Override
    @JsonValue
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static GameMoveEnum fromValue(String text) {
      for (GameMoveEnum b : GameMoveEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("gameMove")
  private GameMoveEnum gameMove = null;

  public Move playerName(String playerName) {
    this.playerName = playerName;
    return this;
  }

   /**
   * Get playerName
   * @return playerName
  **/
  @JsonProperty("playerName")
  @ApiModelProperty(value = "")
  public String getPlayerName() {
    return playerName;
  }

  public void setPlayerName(String playerName) {
    this.playerName = playerName;
  }

  public Move gameMove(GameMoveEnum gameMove) {
    this.gameMove = gameMove;
    return this;
  }

   /**
   * Get gameMove
   * @return gameMove
  **/
  @JsonProperty("gameMove")
  @ApiModelProperty(value = "")
  public GameMoveEnum getGameMove() {
    return gameMove;
  }

  public void setGameMove(GameMoveEnum gameMove) {
    this.gameMove = gameMove;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Move move = (Move) o;
    return Objects.equals(this.playerName, move.playerName) &&
        Objects.equals(this.gameMove, move.gameMove);
  }

  @Override
  public int hashCode() {
    return Objects.hash(playerName, gameMove);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Move {\n");
    
    sb.append("    playerName: ").append(toIndentedString(playerName)).append("\n");
    sb.append("    gameMove: ").append(toIndentedString(gameMove)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

