/*
 * TicTacToe
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the io.swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * Players
 */
@javax.annotation.Generated(value = "io.io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2017-03-21T18:30:20.420Z")
public class Players   {
  @JsonProperty("playerNames")
  private List<String> playerNames = new ArrayList<String>();

  /**
   * Gets or Sets gameType
   */
  public enum GameTypeEnum {
    MULTIPLAYER("MULTIPLAYER"),
    
    SINGLEPLAYER("SINGLEPLAYER");

    private String value;

    GameTypeEnum(String value) {
      this.value = value;
    }

    @Override
    @JsonValue
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static GameTypeEnum fromValue(String text) {
      for (GameTypeEnum b : GameTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("gameType")
  private GameTypeEnum gameType = null;

  public Players playerNames(List<String> playerNames) {
    this.playerNames = playerNames;
    return this;
  }

  public Players addPlayerNamesItem(String playerNamesItem) {
    this.playerNames.add(playerNamesItem);
    return this;
  }

   /**
   * Get playerNames
   * @return playerNames
  **/
  @JsonProperty("playerNames")
  @ApiModelProperty(value = "")
  public List<String> getPlayerNames() {
    return playerNames;
  }

  public void setPlayerNames(List<String> playerNames) {
    this.playerNames = playerNames;
  }

  public Players gameType(GameTypeEnum gameType) {
    this.gameType = gameType;
    return this;
  }

   /**
   * Get gameType
   * @return gameType
  **/
  @JsonProperty("gameType")
  @ApiModelProperty(value = "")
  public GameTypeEnum getGameType() {
    return gameType;
  }

  public void setGameType(GameTypeEnum gameType) {
    this.gameType = gameType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Players players = (Players) o;
    return Objects.equals(this.playerNames, players.playerNames) &&
        Objects.equals(this.gameType, players.gameType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(playerNames, gameType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Players {\n");
    
    sb.append("    playerNames: ").append(toIndentedString(playerNames)).append("\n");
    sb.append("    gameType: ").append(toIndentedString(gameType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

